# Generated by Django 4.1.7 on 2023-06-23 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0003_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('yr1', models.ImageField(blank=True, null=True, upload_to='fyear/')),
                ('yr2', models.ImageField(blank=True, null=True, upload_to='syear/')),
                ('yr3', models.ImageField(blank=True, null=True, upload_to='tyear/')),
            ],
        ),
    ]
