# Generated by Django 4.1.7 on 2023-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='yr1',
            field=models.FileField(blank=True, null=True, upload_to='fyear/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='yr2',
            field=models.FileField(blank=True, null=True, upload_to='syear/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='yr3',
            field=models.FileField(blank=True, null=True, upload_to='tyear/'),
        ),
    ]
